### ISSUE TITLE
How do I remove this error logo from the cards? I don't have any errors with the integration so not sure why they're there.

### ISSUE THREAD

**Issue by claytonaphillips1** [phrz/lg-washer-dryer-card#20]
<img width="78" alt="image" src="https://user-images.githubusercontent.com/53096212/204380110-4a277091-b57b-440d-874b-d8feccba9e90.png">

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/53096212/204380050-f26aa820-ece0-45d7-b3ab-b33a1ca987c3.png">

**Comment by NightMean** [comment]
Check for your entity **sensor.washer_time_display**. I had to change mine to my remaining time entity ID. 

```
type: state-label
        entity: sensor.washer_time_display
        style:
          color: '#8df427'
          font-family: segment7
          font-size: 50px
          left: 95%
          top: 74%
          transform: 'translate(-100%,-50%)'
```
