### ISSUE TITLE
[BUG] 7segment font not used in iOS

### ISSUE THREAD

**Issue by dbell68** [phrz/lg-washer-dryer-card#30]
**Describe the bug**
The washer and dryer cards are working fine except when viewing the card in the Home Assistant app for my iOS device, the 7segment font used for the timer display is not used; seems like just a regular font. Works fine in both desktop and microsoft edge for iOS browsers, and even though the font is incorrect, the remaining time does display correctly.

**What I have tried (required)**
- [X] I checked what the entity name of my washer/dryer/machine is, and it either matches what's in the default configuration (i.e. `sensor.washer`, `sensor.dryer`) or, if it's different, I've modified both `configuration.yaml` and the Lovelace configuration for this card to make it match.
- [X] My LG account is in English, and the state names returned by the LG ThinQ integration are in English, or I've gone through `configuration.yaml` and the Lovelace configuration to change the state tests to the appropriate state strings in my language.
- [X] If my washer/dryer does not look like the one in the default card picture, I've checked that the state names returned by my machine matches the ones in the code, such as showing a hyphen (`'-'`) as the `run_state` entity value when the machine is not running.

**Screenshots**
Sensors:
![washer_states](https://github.com/phrz/lg-washer-dryer-card/assets/49237983/ee63b345-9b00-4491-9e56-bfc8e7601d2d)

HA iOS App Cards
![HA_iOS-Cards](https://github.com/phrz/lg-washer-dryer-card/assets/49237983/0ac8e9c6-3d7f-4833-ab4c-e27feb5a3791)

HA Desktop Browser App Cards
![HA_Desktop_Cards](https://github.com/phrz/lg-washer-dryer-card/assets/49237983/53607a33-96b3-413a-9eed-23546cc9760c)

iOS MS Edge Cards
![iOS_MSEdge_Cards](https://github.com/phrz/lg-washer-dryer-card/assets/49237983/f7a81767-fa18-4d3d-8ba1-943f68a88aa1)

**Template Configuration**
```yaml
- name: washer_door_lock
    #friendly_name: "Washer Door Lock"
    state: "{{ state_attr('sensor.washer','child_lock') }}"

  - name: washer_time_display
    #friendly_name: "Washer Time Display"
    state: >
      {% if is_state('sensor.washer_run_state', '-') %}
      {% elif is_state('sensor.washer_run_state', 'unavailable') %}
      {% elif is_state('sensor.washer_run_state', 'Standby') %}
        -:--
      {% else %}
        {{ state_attr("sensor.washer","remain_time").split(":")[:-1] | join(':') }}   
      {% endif %}
  
  - name: dryer_time_display
    #friendly_name: "Dryer Time Display"
    state: >
        {% if is_state('sensor.dryer_run_state', '-') %}
        {% elif is_state('sensor.dryer_run_state', 'unavailable') %}
        {% elif is_state('sensor.dryer_run_state', 'Standby') %}
          -:--
        {% else %}
          {{ state_attr("sensor.dryer","remain_time").split(":")[:-1] | join(':') }}
        {% endif %}

  - name: blank
    #friendly_name: "Blank Sensor"
    state: ""
```
**Card Configuration**
```yaml
type: picture-elements
elements:
  - type: image
    entity: sensor.washer_run_state
    image: /hacsfiles/lg-wash-dry-card/lg-icons/sensing.png
    state_image:
      Detecting: /hacsfiles/lg-wash-dry-card/lg-icons/sensing-on.png
    style:
      top: 33%
      left: 33%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washer_run_state
    image: /hacsfiles/lg-wash-dry-card/lg-icons/wash.png
    state_image:
      Washing: /hacsfiles/lg-wash-dry-card/lg-icons/wash-on.png
    style:
      top: 33%
      left: 51%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washer_run_state
    image: /hacsfiles/lg-wash-dry-card/lg-icons/rinse.png
    state_image:
      Rinsing: /hacsfiles/lg-wash-dry-card/lg-icons/rinse-on.png
    style:
      top: 33%
      left: 69%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washer_run_state
    image: /hacsfiles/lg-wash-dry-card/lg-icons/spin.png
    state_image:
      Spinning: /hacsfiles/lg-wash-dry-card/lg-icons/spin-on.png
    style:
      top: 33%
      left: 87%
      width: 20%
      image-rendering: crisp
  - type: image
    entity: sensor.washer
    image: /hacsfiles/lg-wash-dry-card/lg-icons/wifi.png
    state_image:
      'on': /hacsfiles/lg-wash-dry-card/lg-icons/wifi-on.png
    style:
      top: 73%
      left: 32%
      width: 10%
      image-rendering: crisp
  - type: image
    entity: sensor.washer_door_lock
    image: /hacsfiles/lg-wash-dry-card/lg-icons/lock.png
    state_image:
      'on': /hacsfiles/lg-wash-dry-card/lg-icons/lock-on.png
    style:
      top: 73%
      left: 45%
      width: 10%
      image-rendering: crisp
  - type: state-label
    entity: sensor.blank
    prefix: '18:88'
    style:
      color: '#555'
      font-family: segment7
      font-size: 50px
      left: 95%
      top: 74%
      transform: translate(-100%,-50%)
  - type: state-label
    entity: sensor.washer_time_display
    style:
      color: '#8df427'
      font-family: segment7
      font-size: 50px
      left: 95%
      top: 74%
      transform: translate(-100%,-50%)
image: /hacsfiles/lg-wash-dry-card/hass-washer-alt-card-bg.png
```
