### ISSUE TITLE
[BUG] Front Load Washer ( ) : Door lock is not relevant

### ISSUE THREAD

**Issue by Jeppedy** [phrz/lg-washer-dryer-card#36]
**Describe the bug**
My current LG integration to my Front-load washer is not returning a functioning Door Lock response.  Always 'Off'.  Confirmed using Dev Tools and run multiple cycles

**What I have tried (required)**
- [XX] I checked what the entity name of my washer/dryer/machine is, and it either matches what's in the default configuration (i.e. `sensor.washer`, `sensor.dryer`) or, if it's different, I've modified both `configuration.yaml` and the Lovelace configuration for this card to make it match.
- [XX] My LG account is in English, and the state names returned by the LG ThinQ integration are in English, or I've gone through `configuration.yaml` and the Lovelace configuration to change the state tests to the appropriate state strings in my language.
- [XX] If my washer/dryer does not look like the one in the default card picture, I've checked that the state names returned by my machine matches the ones in the code, such as showing a hyphen (`'-'`) as the `run_state` entity value when the machine is not running.

This is not a bug in your card.  I simply removed the Door Lock elements and display, since it never changes from 'off'. 
Not sure if you have anything to base this on/customize, but for those coming after, here's my Config and Card.
```
type: vertical-stack
cards:
  - type: picture-elements
    elements:
      - type: image
        entity: sensor.front_load_washer_run_state
        image: /local/lg-icons/sensing.png
        state_image:
          Detecting: /local/lg-icons/sensing-on.png
        style:
          top: 33%
          left: 33%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: /local/lg-icons/wash.png
        state_image:
          Washing: /local/lg-icons/wash-on.png
        style:
          top: 33%
          left: 51%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: /local/lg-icons/rinse.png
        state_image:
          Rinsing: /local/lg-icons/rinse-on.png
        style:
          top: 33%
          left: 69%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer_run_state
        image: /local/lg-icons/spin.png
        state_image:
          Spinning: /local/lg-icons/spin-on.png
        style:
          top: 33%
          left: 87%
          width: 20%
          image-rendering: crisp
      - type: image
        entity: sensor.front_load_washer
        image: /local/lg-icons/wifi.png
        state_image:
          'on': /local/lg-icons/wifi-on.png
        style:
          top: 73%
          left: 32%
          width: 10%
          image-rendering: crisp
      - type: state-label
        entity: sensor.washer_blank
        prefix: '18:88'
        style:
          color: '#555'
          font-family: segment7
          font-size: 50px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
      - type: state-label
        entity: sensor.washer_time_display
        style:
          color: '#8df427'
          font-family: segment7
          font-size: 50px
          left: 95%
          top: 74%
          transform: translate(-100%,-50%)
    image: /local/hass-washer-alt-card-bg.png
  - type: entities
    entities:
      - type: attribute
        entity: sensor.front_load_washer
        attribute: tubclean_count
        name: Washer Cycles Since Cleaned
  - type: conditional
    conditions:
      - entity: sensor.front_load_washer_run_state
        state_not: '-'
    card:
      type: entities
      entities:
        - entity: sensor.front_load_washer
          type: attribute
          attribute: end_time
          name: Est End Time
          icon: mdi:clock-end

```

```
- platform: template
  sensors:
    washer_blank:
      friendly_name: "Washer Blank Sensor"
      value_template: ""
#    washer_door_lock:
#      friendly_name: "Washer Door Lock"
#      value_template: "{{ state_attr('sensor.front_load_washer','door_lock') }}"

    washer_time_display:
        friendly_name: "Washer Time Display"
        value_template: >
            {% if is_state('sensor.front_load_washer_run_state', '-') %}
            {% elif is_state('sensor.front_load_washer_run_state', 'unavailable') %}
            {% elif is_state('sensor.front_load_washer_run_state', 'Standby') %}
               -:--
            {% elif is_state('sensor.front_load_washer_run_state', 'Delay Set') %}
               {{ state_attr("sensor.front_load_washer","reserve_time").split(":")[:-1] | join(':') }}          
            {% else %}
               {{ state_attr("sensor.front_load_washer","remain_time").split(":")[:-1] | join(':') }}   
            {% endif %}

```
